# use it when deployed
#SPRING_APPLICATION_NAME=chat-app-backend
#SERVER_PORT=8090
#SPRING_DATA_MONGODB_URI=mongodb+srv://loknathsaha2004:Iamsurya2004@loknathdb.9xxyuz3.mongodb.net/chat-app

spring.application.name=chat-app-backend
server.port=8090
spring.data.mongodb.uri=mongodb+srv://loknathsaha2004:Iamsurya2004@loknathdb.9xxyuz3.mongodb.net/chat-app


# Set the root logging level to INFO
logging.level.root=INFO

# Set security logging to DEBUG to see filter chain decisions
logging.level.org.springframework.security=DEBUG

# Set web logging to TRACE to see request details and CORS handling
logging.level.org.springframework.web=TRACE